apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: five-per-min
config:
  minute: 5
  policy: local
plugin: rate-limiting
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: q5ingress
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: five-per-min
spec:
  rules:
    - http:
        paths:
          - path: "/v1/tasks/task"
            pathType: Prefix
            backend:
              service:
                name: producer
                port:
                  number: 80
          - path: "/v1/hello"
            pathType: Prefix
            backend:
              service:
                name: q4ans
                port:
                  number: 80
